using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace Domain.Entities.Auth
{
    public class SystemOptions
    {
        public string MASTER_INDEX_FLAG { get; set; }
        public string MULTIPRACTICE_PATIENT_FLAG { get; set; }
        public string LEDGER_PRACTICE_EQ_CHARGE { get; set; }
        public string CLAIM_EDIT { get; set; }
        public string READY_CLAIM_FLAG { get; set; }
        public string RESUBMIT_CLAIM_FLAG { get; set; }
        public string SEQUELMED_TYPE { get; set; }
        public string SEQUELMED_VERSION { get; set; }
        public long ENTITY_SEQ_NUM { get; set; }
        public string MULTIPLE_LEDGERS { get; set; }
        public string UNICOR_EDITING { get; set; }
        public string CHARGE_BATCH_REQUIRED { get; set; }
        public string PATIENT_LOCATION_DEFAULT { get; set; }
        public string EOB_PRACTICE_REQUIRED { get; set; }
        public string LEDGER_BATCH_REQUIRED { get; set; }
        public string FTP_HOSTNAME { get; set; }
        public string FTP_ALIAS { get; set; }
        public string CHARGE_UNIQNES { get; set; }
        public string PLAN_MASTER_INDEX_FLAG { get; set; }
        public string HOSPITALIST_CASE_MANAGEMENT { get; set; }
        public DateTime SCHEDULER_CLAIM_EDITING_RUN { get; set; }
        public DateTime SCHEDULER_CLAIM_SUBMIT_RUN { get; set; }
        public DateTime SCHEDULER_EDI_REPORT_RUN { get; set; }
        public string PLAN_ID_FORMAT_ENFORCE { get; set; }
        public long CHARGE_ENTRY_OPTION { get; set; }
        public string DELETE_LEDGER { get; set; }
        public long FEED_REPOSITORY_PRACT_SEQ_NUM { get; set; }
        public string ANESTHESIA_UNIT_FEE_SCHEDULE { get; set; }
        public string FAMILY_INDEX { get; set; }
        public string CHARGE_BATCH_CLOSE_REQ { get; set; }
        public long CHARGE_TAB_ORDER { get; set; }
        public string SEQUELMED_NEW_TYPE { get; set; }
        public char[] INTEGRATOR_TYPE { get; set; }
        public string UPS_LABELS { get; set; }
        public string PLAN_NFWC_TRANSFER_OPTION { get; set; }
        public string REF_PROF_FIND_CRITERIA_FLAG { get; set; }
        public string EOD_BY { get; set; }
        public string PAYMENT_BATCH_PRACT_OPTIONAL { get; set; }
        public string SEQUEL_FTP_HOSTNAME { get; set; }
        public string SEQUEL_FTP_ALIAS { get; set; }
        public string SEQUEL_SMTP { get; set; }
        public string CLIENT_NAME { get; set; }
        public string STS_IIS_USER_NAME { get; set; }
        public long EDI_CLIENT_ID { get; set; }
        public string LOCK_CHARGES_FLAG { get; set; }
        public string CLAIM_STAKER_FLAG { get; set; }
        public string EMR_INTEGRATION { get; set; }
        public string EMR_FLAG { get; set; }
        public string CLIENT_SIZE { get; set; }
        public string IPA_FLAG { get; set; }
        public string CURRENT_DB_VERSION { get; set; }
        public string AUTO_ALLOWED_APPLY { get; set; }
        public long ALLOWED_WARNING_COLOR { get; set; }
        public long ALLOWED_ERROR_COLOR { get; set; }
        public string ENTITY_OPTION { get; set; }
        public long NEXT_POOL_TIME { get; set; }
        public long PASSWORD_MINIMUM_LENGTH { get; set; }
        public string PASSWORD_ALPHANUMERIC_FLAG { get; set; }
        public string CASE_SENSITIVE_PASSWORD { get; set; }
        public long PASSWORD_TRIES { get; set; }
        public long PROVIDER_LICENSE { get; set; }
        public long USER_LICENSE { get; set; }
        public string ADDENDUM_MODE { get; set; }
        public string LAB_CLIENT_PASSWORD { get; set; }
        public string LAB_POOL_INTERVAL { get; set; }
        public string EMR_CURRENT_DB_VERSION { get; set; }
        public string EPM_FLAG { get; set; }
        public string EMR_APP_VERSION { get; set; }
        public string INSTALLED_TYPE { get; set; }
        public string DB_TYPE { get; set; }
        public DateTime EXPIRATION_DATE { get; set; }
        public string PRODUCT_KEY { get; set; }
        public long DAYS_LEFT { get; set; }
        public DateTime START_DATE { get; set; }
        public long NUMBER_OF_PATIENTS { get; set; }
        public long NO_OF_DAYS { get; set; }
        public string PROVIDER_PIN_EIN { get; set; }
        public string EMR_SECURITY_VERSION { get; set; }
        public string CLINICAL_LIBRARY_VERSION { get; set; }
        public string CLIENT_ID { get; set; }
        public string INPATIENT_FLAG { get; set; }
        public string CHARGE_DELETE_OPTION { get; set; }
        public string ROAMING_PROFILE { get; set; }
        public string HL7_PLAN_ADDRESS_FLAG { get; set; }
        public string AUTO_PROCESS_EMR_CHARGE { get; set; }
        public string BI_URL { get; set; }
        public string WAREHOUSE { get; set; }
        public string HOSPITAL_FEED { get; set; }
        public string ALLOW_ALL_PROVIDERS { get; set; }
        public long RX_DEFAULT_PAT_SEQ_NUM { get; set; }
        public string EPM_INTERFACE_INFO { get; set; }
        public string PATIENT_PORTAL_FLAG { get; set; }
        public string PNOTE_SHARE { get; set; }
        public string ELINK_INFO { get; set; }
        public long PORTAL_PATIENT_LEDGER { get; set; }
        public long PORTAL_COPAY_LEDGER { get; set; }
        public long PORTAL_ADVANCE_LEDGER { get; set; }
        public string CUSTOM_RX_PRINT_TEXT { get; set; }
        public string AUTOSAVE_HPI { get; set; }
        public string LOGIN_BANNER { get; set; }
        public string GCODE_FLAG { get; set; }
        public string PHR_STATEMENT_URL { get; set; }
        public string BUYER_NAME { get; set; }
        public string RHIO_FLAG { get; set; }
        public string SEND_XML_ON_SIGNOFF { get; set; }
        public long INK_RATIO { get; set; }
        public DateTime WAREHOUSE_LEDGER_EOD { get; set; }
        public string FAXMAN_FLAG { get; set; }
        public string EREFILL_USER { get; set; }
        public string RX_REQUEST_OPTIONS { get; set; }
        public string UPDATE_EMR_PATIENT { get; set; }
        public string ELIGIBILITY_UPDATE_PLAN { get; set; }
        public string EC_FLAG { get; set; }
        public string EDI_SERVICES_URL { get; set; }
        public string MSP_FLAG { get; set; }
        public string SPLIT_MULTI_APPT { get; set; }
        public string PORTAL_MAIL_SERVICE { get; set; }
        public string DOS_IS_ADMISSION_DATE { get; set; }
        public long DEFAULT_LAB_PROVIDER { get; set; }
        public string IGNORE_ADMIT_DATE_CHECK { get; set; }
        public string LAB_AUTO_NOTIFICATION { get; set; }
        public long ZERO_LEDGER_SEQ_NUM { get; set; }
        public string PAYMENT_BATCH_CHECK_DATE_FLAG { get; set; }
        public DateTime LIC_VIOLATION_DT { get; set; }
        public long LIC_VIOLATION_WARNING_DAYS { get; set; }
        public string NEW_MODIFIER_FEE { get; set; }
        public string UB04 { get; set; }
        public string WC_PDF_FLAG { get; set; }
        public string WCB_EDI_TYPE { get; set; }
        public string EMR_READY_CLAIM_FLAG { get; set; }
        public long ALLOWED_WRITEOFF_SEQ_NUM { get; set; }
        public string UB04_CASE_NUM_TYPE { get; set; }
        public string USER_RESTRICTION { get; set; }
        public string EPM_DASHBOARD_URL { get; set; }
        public long ELIG_FUTURE_DAYS { get; set; }
        public long ELIG_DAYS_PAT_REGISTRATION { get; set; }
        public string SEQUEL_SCRUBBER_FLAG { get; set; }
        public string SEQUEL_SCRUBBER_URL { get; set; }
        public string EDM_SYNCING_FLAG { get; set; }
        public char[] EDM_ARCHIVE_FLAG { get; set; }
        public string EDM_ARCHIVE_HOSTNAME { get; set; }
        public string EDM_ARCHIVE_ALIAS { get; set; }
        public string EPM_EMR_FLAG { get; set; }
        public string CLINICAL_TASK_TAG_FLAG { get; set; }
        public string CLAIMSCRUBBER_URL { get; set; }
        public string EMR_CLIENT_APP_UPDATE_URL { get; set; }
        public string XML_IN_DB { get; set; }
        public string SERVER_SIDE_SIGN_OFF { get; set; }
        public string EPM_LOCAL_DIR { get; set; }
        public string ICD10_FLAG { get; set; }
        public string EMRPM_CURRENT_VERSION { get; set; }
        public string IS_SCREENED { get; set; }
        public string IS_GLASS_SUPPORTED { get; set; }
        public string CLASS_SKIP_SEARCH_LIST { get; set; }
        public string ISCHIRO { get; set; }
        public string ISPT { get; set; }
        public string TAXONOMY_CODE { get; set; }
        public string HCFA_PAGING_FLAG { get; set; }
        public string ERA_LINKING_MODE { get; set; }
        public string EDI360_SETUP { get; set; }
        public string IEHR_CURRENT_DB_VERSION { get; set; }
        public string CLINICAL_SERVICE_HOST { get; set; }
        public long IEHR_SCHEDULE_DAYS { get; set; }
        public string DEFAULT_LAB_PATIENT_VIEW { get; set; }
        public char[] ELIG_UPDAE_PLAN_WITHOUT_COPAY { get; set; }
        public string UPDATE_PROV_PIN { get; set; }
        public string PDF_TO_TIF_FLAG { get; set; }
        public string REPORT_ASSIST_PROV { get; set; }
        public string PRINTER_NATIVE_CALL { get; set; }
        public string IS_EMR_SCURBBER_FLAG { get; set; }
        public string IEHR_INTEGRATION { get; set; }
        public long EMR_EPM_VENDOR_SEQ_NUM { get; set; }
        public char[] ISICD10 { get; set; }
        public DateTime CUT_OFF_DATE { get; set; }
        public string SNOMED_TO_ICD { get; set; }
        public long DASHBOARD_REFRESH_TIME { get; set; }
        public string RETURN_ZERO_SLOT { get; set; }
        public string CLAIM_EDITING_PAT_ELIGIBILITY { get; set; }
        public string WCNF_FOR_ALL { get; set; }
        public string PROCESS_SAME_CHECK { get; set; }
        public string APPLY_ACTIVE_PLAN { get; set; }
        public string REPORT_PROV_WCB_AUTH { get; set; }
        public string RECALC_ERA_WRITEOFF1 { get; set; }
        public string EDI_SIMPLIFIED_CLAIM_STATUS { get; set; }
        public string IS_CALCUALTE_EXPECTED { get; set; }
        public string CHK_NAME_ADDR_FOR_BILLING_LOO { get; set; }
        public string ALLOW_PARTIAL_TRANSFER_TO_PLA { get; set; }
        public string IS_FOLLOWUP_CALL_MANDATORY { get; set; }
        public char[] CHECKOUT_COPAY_VALIDATION { get; set; }
        public string PLAN_SUBSET { get; set; }
        public string ENABLE_VISIT_LOCATION { get; set; }
        public string TRANS_FIRST { get; set; }
        public string EXOSTAR_FAQ_URL { get; set; }
        public string PROVIDER_FAQ_URL { get; set; }
        public string EXOSTAR_RETURN_URL { get; set; }
        public string FAX_BOOK { get; set; }
        public string EXOSTAR_URL { get; set; }
        public string EPCS_INCIDENT_REPORT_USER { get; set; }
        public string SECHEDULE_2_APPROVE { get; set; }
        public string EPCS_FROM_TIME { get; set; }
        public string EPCS_TO_TIME { get; set; }
        public string CSSN_LICENCE_KEY { get; set; }
        public string TNS_NAME { get; set; }
        public string PATIENT_TRACKER_BOARD_URL { get; set; }
        public long UB_VENDOR_SEQ_NUM { get; set; }
        public string FAX_AUTOMATION { get; set; }
        public string AUTO_CLAIM_STATUS { get; set; }
        public string AUTO_STATEMENT { get; set; }
        public char[] AUTO_SUBMISSION { get; set; }
        public string COPY_PASTE_SCREENING { get; set; }
        public string COPY_PASTE_SCREENING_SECTION { get; set; }
        public long EXTERNAL_EDI_VENDOR { get; set; }
        public string OVERRIDE_ZERO_LEDGER { get; set; }
        public string EPCS_SCHEDULE_URL { get; set; }
        public string ELIG_BY_GROUP { get; set; }
        public string SSN_ON_STATEMENT { get; set; }
        public string REPORT_PLAN_DESCRIPTION { get; set; }
        public string COVID_ORDERSET_FLOW { get; set; }
        public string COPAY_ON_START_PROCESS { get; set; }
        public string PLAN_ON_START_PROCESS { get; set; }

    }
}
